### ISSUE TITLE
Purpose of this repo

### ISSUE THREAD

**Issue by stof** [php-pds/pds#1]
While looking at the repositories in the php-pds organization, I found this repository quite confusing.
It has no readme explaining its purpose, and the composer.json describes it as a "PHP Data Sets implementation".
What is this repo about ?

**Comment by wkhayrattee** [comment]
Hi @stof ,

Not sure, but I think this repo will be an implementation showcase of https://github.com/php-pds/skeleton (http://php-pds.com/).
